version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
       MYSQL_DATABASE: 'gerenciamento_estagio'
       MYSQL_ALLOW_EMPTY_PASSWORD: 1
       MYSQL_ROOT_PASSWORD: ""
       MYSQL_TCP_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
